version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Pre-build phase
  build:
    commands:
      - echo Build phase
      - cd src && make package S3_BUCKET=$S3_ARTIFACT_BUCKET S3_PREFIX="packaged/commit-$COMMIT_HASH"
  post_build:
    commands:
      - echo Post-build phase

artifacts:
  files:
    - '**/*'
    - 'resources.params.dev.json'